from pymouse import PyMouse
from pykeyboard import PyKeyboard
import time

m = PyMouse()
k = PyKeyboard()
x_dim, y_dim = m.screen_size()

m.click(x_dim*.95, y_dim/2, 1)
time.sleep(.1)
k.press_key(k.alt_key)
time.sleep(.1)
k.tap_key(k.tab_key)
time.sleep(.1)
k.tap_key(k.tab_key)
time.sleep(.1)
k.release_key(k.alt_key)
time.sleep(.1)
m.click(x_dim/2, y_dim/2, 1)
time.sleep(.1)
k.press_key(k.alt_key)
time.sleep(.1)
k.tap_key(k.tab_key)
time.sleep(.1)
k.release_key(k.alt_key)
time.sleep(.1)

for _ in range(50):
  m.click(x_dim*.95, y_dim/2, 1)
  time.sleep(.1)
  k.press_key(k.control_key) 
  time.sleep(.1)
  k.type_string('a')
  time.sleep(.1)
  k.release_key(k.control_key)
  time.sleep(.1)
  k.press_key(k.control_key)
  time.sleep(.1)
  k.type_string('c')
  time.sleep(.1)     
  k.release_key(k.control_key)
  time.sleep(.1) 
  k.press_key(k.alt_key)
  time.sleep(.1)
  k.tap_key(k.tab_key)
  time.sleep(.1)
  k.release_key(k.alt_key)
  time.sleep(.1)         
  k.press_key(k.control_key)
  time.sleep(.1)
  k.type_string('v')
  time.sleep(.1)
  k.release_key(k.control_key)
  time.sleep(.1) 
  k.press_key(k.alt_key)
  time.sleep(.1)
  k.tap_key(k.tab_key)
  time.sleep(.1)
  k.release_key(k.alt_key)
  time.sleep(.5)
  k.tap_key(k.next_key)
  time.sleep(.5)
  k.tap_key(k.next_key)
  time.sleep(.5)
  k.tap_key(k.next_key)
  time.sleep(2)  
  m.click(x_dim/2, y_dim*.8, 1)
  time.sleep(90)
 

